services:
  nethermind:
    image: fiftysix/nethermind:latest
    container_name: nethermind
    command: >
      nethermind
      --datadir /node/nethermind/data
      --JsonRpc.JwtSecretFile /node/nethermind/data/jwt.hex
      --Init.WebSocketsEnabled "true"
      --Network.MaxActivePeers "50"
      --HealthChecks.Enabled "true"
      --HealthChecks.UIEnabled "true"
      --JsonRpc.Enabled "true"
      --JsonRpc.Host "0.0.0.0"
      --JsonRpc.Port "8545"
      --JsonRpc.WebSocketsPort "8546"
      --JsonRpc.EngineHost "0.0.0.0"
      --JsonRpc.EnginePort "8551"
    ports:
      - "8545:8545"
      - "8546:8546"
      - "8551:8551"
      - "30303:30303/tcp"
      - "30303:30303/udp"
    volumes:
      - nethermind-data:/node/nethermind
    networks:
      - ethereum-net

  prysm:
    image: gcr.io/prysmaticlabs/prysm/beacon-chain:stable
    command: >
      --accept-terms-of-use
      --datadir=/node/prysm/data/
      --jwt-secret=/node/nethermind/data/jwt.hex
      --rpc-host=0.0.0.0
      --grpc-gateway-host=0.0.0.0
      --monitoring-host=0.0.0.0
      --execution-endpoint=http://nethermind:8551
      --checkpoint-sync-url=https://beaconstate.info
      --genesis-beacon-api-url=https://beaconstate.info
    container_name: prysm
    ports:
      - "3500:3500"
      - "4000:4000"
      - "12000:12000"
      - "13000:13000"
    depends_on:
      - nethermind
    volumes:
      - nethermind-data:/node/nethermind
      - prysm-data:/node/prysm
    networks:
      - ethereum-net

networks:
  ethereum-net:
    driver: bridge

volumes:
  nethermind-data:
  prysm-data:
