services:
  geth:
    image: geth:1.14.2 #fiftysix/geth:latest
    container_name: geth
    command: >
      geth
      --mainnet
      --syncmode "snap"
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30303:30303/tcp"
      - "30303:30303/udp"
    volumes:
      - geth-data:/node/geth
    networks:
      - ethereum-net

  lighthouse:
    image: sigp/lighthouse
    container_name: lighthouse
    volumes:
      - geth-data:/node/geth
      - lighthouse-data:/root/.lighthouse
    ports:
      - "9000:9000/tcp"
      - "9000:9000/udp"
      - "9001:9001/udp"
      - "5052:5052"
    depends_on:
      - geth
    command: >
      lighthouse
      bn
      --network mainnet
      --execution-endpoint http://geth:8551
      --execution-jwt /node/geth/data/jwt.hex
      --checkpoint-sync-url https://beaconstate.ethstaker.cc
      --http
      --http-address 0.0.0.0
      --disable-deposit-contract-sync
    networks:
      - ethereum-net

networks:
  ethereum-net:
    driver: bridge

volumes:
  geth-data:
  lighthouse-data:
