services:
  nethermind:
    image: fiftysix/nethermind:latest
    container_name: nethermind
    command: >
      nethermind
      --datadir /node/nethermind/data
      --JsonRpc.JwtSecretFile /node/nethermind/data/jwt.hex
      --Init.WebSocketsEnabled "true"
      --Network.MaxActivePeers "50"
      --HealthChecks.Enabled "true"
      --HealthChecks.UIEnabled "true"
      --JsonRpc.Enabled "true"
      --JsonRpc.Host "0.0.0.0"
      --JsonRpc.Port "8545"
      --JsonRpc.WebSocketsPort "8546"
      --JsonRpc.EngineHost "0.0.0.0"
      --JsonRpc.EnginePort "8551"
    ports:
      - "8545:8545"
      - "8546:8546"
      - "8551:8551"
      - "30303:30303/tcp"
      - "30303:30303/udp"
    volumes:
      - nethermind-data:/node/nethermind
    networks:
      - ethereum-net

  lodestar:
    image: chainsafe/lodestar:next
    container_name: lodestar
    volumes:
      - nethermind-data:/node/nethermind
      - lodestar-data:/data
    ports:
      - "9000:9000" # P2P port
      - "9596:9596" # REST API port
    depends_on:
      - nethermind
    command: >
      beacon
      --network mainnet
      --execution.urls http://nethermind:8551
      --dataDir /data
      --rest
      --rest.address 0.0.0.0
      --jwtSecret /node/nethermind/data/jwt.hex
      --metrics
      --logFile /logs/beacon.log
      --logFileLevel debug
      --logFileDailyRotate 5
      --checkpointSyncUrl https://beaconstate.ethstaker.cc
    # NodeJS applications have a default memory limit of 4GB on most machines.
    # This limit is bit tight for a Mainnet node, it is recommended to raise the limit
    # since memory may spike during certain network conditions.
    environment:
      NODE_OPTIONS: --max-old-space-size=8192
    networks:
      - ethereum-net

networks:
  ethereum-net:
    driver: bridge

volumes:
  nethermind-data:
  lodestar-data:
