services:
  nethermind:
    image: nethermind:1.26.0
    container_name: nethermind
    command: >
      nethermind
      --datadir /node/nethermind/data
      --JsonRpc.JwtSecretFile /node/nethermind/data/jwt.hex
      --Init.WebSocketsEnabled "true"
      --Network.MaxActivePeers "50"
      --HealthChecks.Enabled "true"
      --HealthChecks.UIEnabled "true"
      --JsonRpc.Enabled "true"
      --JsonRpc.Host "0.0.0.0"
      --JsonRpc.Port "8545"
      --JsonRpc.WebSocketsPort "8546"
      --JsonRpc.EngineHost "0.0.0.0"
      --JsonRpc.EnginePort "8551"
    ports:
      - "8545:8545"
      - "8546:8546"
      - "8551:8551"
      - "30303:30303/tcp"
      - "30303:30303/udp"
    volumes:
      - nethermind-data:/node/nethermind
    networks:
      - ethereum-net

  lighthouse:
    image: sigp/lighthouse
    container_name: lighthouse
    volumes:
      - nethermind-data:/node/nethermind
      - lighthouse-data:/root/.lighthouse
    ports:
      - "9000:9000/tcp"
      - "9000:9000/udp"
      - "9001:9001/udp"
      - "5052:5052"
    depends_on:
      - nethermind
    command: >
      lighthouse
      bn
      --network mainnet
      --execution-endpoint http://nethermind:8551
      --execution-jwt /node/nethermind/data/jwt.hex
      --checkpoint-sync-url https://beaconstate.ethstaker.cc
      --http
      --http-address 0.0.0.0
      --disable-deposit-contract-sync
    networks:
      - ethereum-net

networks:
  ethereum-net:
    driver: bridge

volumes:
  nethermind-data:
  lighthouse-data:
