services:
  besu:
    image: fiftysix/besu:latest
    container_name: besu
    ports:
      - "8545:8545"
      - "8546:8546"
      - "8551:8551"
      - "30303:30303/tcp"
      - "30303:30303/udp"
    volumes:
      - besu-data:/node/besu
    networks:
      - ethereum-net

  prysm:
    image: gcr.io/prysmaticlabs/prysm/beacon-chain:stable
    command: >
      --accept-terms-of-use
      --datadir=/node/prysm/data/
      --jwt-secret=/node/besu/data/jwt.hex
      --rpc-host=0.0.0.0
      --grpc-gateway-host=0.0.0.0
      --monitoring-host=0.0.0.0
      --execution-endpoint=http://besu:8551
      --checkpoint-sync-url=https://beaconstate.info
      --genesis-beacon-api-url=https://beaconstate.info
    container_name: prysm
    ports:
      - "3500:3500"
      - "4000:4000"
      - "12000:12000"
      - "13000:13000"
    depends_on:
      - besu
    volumes:
      - besu-data:/node/besu
      - prysm-data:/node/prysm
    networks:
      - ethereum-net

networks:
  ethereum-net:
    driver: bridge

volumes:
  besu-data:
  prysm-data:
