[Node]
DataDir = "/node/geth/"
IPCPath = "geth.ipc"
HTTPPort = 8545
HTTPModules = ["net", "web3", "eth"]
WSPort = 8546
WSModules = ["net", "web3", "eth"]

[Node.P2P]
MaxPeers = 50
NoDiscovery = false
ListenAddr = ":30303"

#[Dashboard]
#Host = "localhost"
#Port = 8080
#Refresh = 5000000000

