services:
  bitcoin-node:
    image: bitcoin-core:27.0 #fiftysix/bitcoin-core:latest
    container_name: bitcoin-core
    ports:
      - "8332:8332"
      - "8333:8333"
    volumes:
      - bitcoin-data:/node
    networks:
      - bitcoin-net

networks:
  bitcoin-net:
    driver: bridge

volumes:
  bitcoin-data:

