services:
  bitcoin-core:
    image: fiftysix/bitcoin-core:latest
    container_name: bitcoin-core
    ports:
      - "8332:8332"
      - "8333:8333"
    volumes:
      - bitcoin-core-data:/node/bitcoin-core
    networks:
      - bitcoin-net

  ord:
    image: fiftysix/ord:latest
    command: ord --bitcoin-rpc-url http://bitcoin-core:8332 server
    container_name: ord
    ports:
      - "80:80"
    depends_on:
      - bitcoin-core
    volumes:
      - bitcoin-core-data:/node/bitcoin-core
      - ord-data:/node/ord
    networks:
      - bitcoin-net

networks:
  bitcoin-net:
    driver: bridge

volumes:
  bitcoin-core-data:
  ord-data:
